include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Güvenlik
    avoid_print: true
    avoid_dynamic_calls: true

    # Riverpod / state
    avoid_unnecessary_containers: true
    use_key_in_widget_constructors: true

    # Kod kalitesi
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    unnecessary_string_interpolations: true
    unnecessary_nullable_for_final_variable_declarations: true

    # Import
    always_use_package_imports: false
    prefer_relative_imports: true

    # Null safety
    prefer_null_aware_operators: true

    # Dart style
    sort_constructors_first: true
    sized_box_for_whitespace: true
    use_super_parameters: true
